[package]
name = "starknetbook_chapter_2"
version = "0.1.0"

[scripts]
setup = "export STARKNET_NETWORK=alpha-goerli && export STARKNET_WALLET=starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount"
declare = "starknet declare --contract target/dev/starknetbook_chapter_2_Vote.sierra.json  --account vote_admin"
deploy = "starknet deploy --class_hash 0x7cee474b26f127c9152dc68fa4293fc8094681fc97ac7a6e3ecd8eb28e3d54e --inputs 0x4d77bb090f6d4a11662cc007995d9026015b13c0264094aa1f246d9200a604a 1 0 --account vote_admin --max_fee 100000000000000000"
call = "starknet call --function voter_can_vote --inputs 0x4d77bb090f6d4a11662cc007995d9026015b13c0264094aa1f246d9200a604a --address 0x05f12c32b051a9799f2b91f1b8c903b97da7e0219cad201cd1266cc0dbcccced --account vote_admin"
invoke = "starknet invoke --function vote --address 0x05f12c32b051a9799f2b91f1b8c903b97da7e0219cad201cd1266cc0dbcccced --inputs 1 --account vote_admin --max_fee 100000000000000000"
call_status = "starknet call --function get_vote_status --address 0x05f12c32b051a9799f2b91f1b8c903b97da7e0219cad201cd1266cc0dbcccced --account vote_admin"

[dependencies]
starknet = "2.0.0-rc3"

[[target.starknet-contract]]
# Enable Sierra codegen.
sierra = true
# Enable CASM codegen.
casm = false